### ISSUE TITLE
Replace create_boxscore by the constructor of Boxscore

### ISSUE THREAD

**Issue by J-Merle** [Bobbyberu/TTFL-Dashboard#27]
https://github.com/Bobbyberu/TTFL-Dashboard/blob/542e9a2e5ff339bcb53a2c692124e2be1989422a/back/ttfl_dashboard_api/db_models.py#L72

The function `create_boxcore` shouldn't exist.
Use instead the constructor `__init__` of `Boxscore`

**Comment by Bobbyberu** [comment]
i created this function cause i had to calculate ttfl_points from parameters that i send here, and since i think it is not possible in peewee objects constructors i chose to make this function (feel free to enlight me if im wrong)
